### ISSUE TITLE
決定要期末專案要做什麼

### ISSUE THREAD

**Issue by Vdragon** [NTOUCS-Java-Programming-103-Team-13/youtube-dl-helper#1]
請在下面提出你的提案，這禮拜結束前再表決吧？

GitHub 貼文支援 Markdown 語法，Markdown 語法可以參考 [Markdown 語法說明](http://markdown.tw/)

**Comment by stevekevin1005** [comment]
馬利歐

**Comment by Vdragon** [comment]
# youtube-dl wrapper 圖形介面程式

## youtube-dl 是什麼？

[youtube-dl](http://rg3.github.io/youtube-dl/) 為下載 Youtube 與[更多線上影音網站](http://rg3.github.io/youtube-dl/supportedsites.html)多媒體的命令列介面下載程式

## 類似性質的專案
- [jakeogh/youtube-dl-wrapper](https://github.com/jakeogh/youtube-dl-wrapper)
- [fredyw/win-youtube-dl](https://github.com/fredyw/win-youtube-dl)
  - 根據開發者說明理論上 Mac、GNU/Linux 平台也能執行，但是目前只有提供 Windows 平台的程式

**Comment by Vdragon** [comment]
@stevekevin1005 有空的話麻煩簡單描述您的提案內容

**Comment by stevekevin1005** [comment]
http://pic2.52pk.com/files/110315/3390_105616_1_lit.jpg

像是這種遊戲~

**Comment by stevekevin1005** [comment]
https://www.youtube.com/channel/UCiSLpKwBTxyHy3UqBgUCWQw

**Comment by Vdragon** [comment]
決定用 youtube-dl-wrapper
